name    'lex-dnsmasq'
version '2.2.0'
dependency 'puppetlabs/concat', '>= 1.0.0'
source 'git://github.com/rlex/puppet-dnsmasq.git'
author 'Lex Rivera <me@lex.io>'
license 'Creative Commons Attribution 3.0 Unported License'
summary 'Puppet Dnsmasq management module'
description 'A module to deploy and manage the dnsmasq DNS/DHCP/TFTP server'
project_page 'https://github.com/rlex/puppet-dnsmasq'
