name    'puppet-dnsmasq'
version '1.1.0'
dependency 'puppetlabs/stdlib', '>= 2.2.1'
source 'git://github.com/rlex/puppet-dnsmasq.git'
author 'Lex Rivera <me@lex.io>'
license 'Creative Commons Attribution 3.0 Unported License'
summary 'Puppet Dnsmasq management module'
description 'A module to deploy and manage the dnsmasq DNS/DHCP/TFTP server'
project_page 'https://github.com/rlex/puppet-dnsmasq'
